version = 1
SPDX-PackageName = "OCM Delivery Service"
SPDX-PackageSupplier = "Christian Cwienk <christian.cwienk@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/open-component-model/delivery-service"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2024 SAP SE or an SAP affiliate company and Open Component Model contributors \\", "<christian.cwienk@sap.com>"]
SPDX-License-Identifier = "Apache-2.0"
