kubeconfig:
  apiVersion: v1
  kind: Config
  current-context: odg-cluster
  contexts:
    - name: odg-cluster
      context:
        cluster: odg-cluster
        user: odg-cluster
  clusters:
    - name: odg-cluster
      cluster:
        server: ... # string
        certificate-authority-data: ... # string
  users:
    - name: odg-cluster
      user:
        token: ... # string
